version: 2

project_name: easyp

builds:
  - binary: easyp
    main: ./cmd/easyp/
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '(?i)^docs?:'
      - '(?i)^docs\([^:]+\):'
      - '(?i)^docs\[[^:]+\]:'
      - '^tests?:'
      - '(?i)^dev:'
      - '(?i)^chore:'
      - '^build\(deps\): bump .* in /docs \(#\d+\)'
      - '^build\(deps\): bump .* in /\.github/peril \(#\d+\)'
      - '^build\(deps\): bump .* in /scripts/gen_github_action_config \(#\d+\)'
      - Merge pull request
      - Merge branch

release:
  skip_upload: false
  github:
    owner: easyp-tech
    name: easyp
  header: |
    `easyp` is a free and open-source project built by volunteers.

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

brews:
  - description: Easy modern protobuf tooling for all your needs.
    homepage: https://easyp.tech
    skip_upload: false
    repository:
      owner: easyp-tech
      name: homebrew-tap
    commit_author:
      name: easyp-tech-releaser
      email: action@github.com
    directory: Formula
    install: |
      bin.install "easyp"
      output = Utils.popen_read("#{bin}/easyp completion bash")
      (bash_completion/"easyp").write output
      output = Utils.popen_read("#{bin}/easyp completion zsh")
      (zsh_completion/"_easyp").write output
      prefix.install_metafiles
    test: |
      system "#{bin}/easyp --version"
