package core

import (
	"context"
	"fmt"
	"path/filepath"
	"sync"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	pluginexecutor "github.com/easyp-tech/easyp/internal/adapters/plugin"
)

type goOutputExecutor struct {
	responses map[string]*pluginpb.CodeGeneratorResponse
}

func (e *goOutputExecutor) Execute(_ context.Context, info pluginexecutor.Info, _ *pluginpb.CodeGeneratorRequest) (*pluginpb.CodeGeneratorResponse, error) {
	return proto.Clone(e.responses[info.Source]).(*pluginpb.CodeGeneratorResponse), nil
}

func (e *goOutputExecutor) GetName() string {
	return "goOutputExecutor"
}

func TestExecuteIntoInsertionUsesProducerOutputPath(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		insertionName string
		insertionOut  string
		options       map[string][]string
		separatePlans bool
		duplicate     bool
		ambiguous     bool
		wantError     string
	}{
		{name: "insertion without paths option", insertionName: "api/user_grpc.pb.go", insertionOut: "gen"},
		{name: "overlapping grpc basename", insertionName: "api/user_grpc.pb.go", insertionOut: "gen", options: map[string][]string{"paths": {"source_relative"}}},
		{name: "different insertion mapping", insertionName: "api/user_grpc.pb.go", insertionOut: "gen", options: map[string][]string{"paths": {"source_relative"}, "Mapi/user.proto": {"example.test/generated/other"}}},
		{name: "shared bucket across plans", insertionName: "api/user_grpc.pb.go", insertionOut: "gen", separatePlans: true},
		{name: "already relocated insertion name", insertionName: "user/v1/user_grpc.pb.go", insertionOut: "gen"},
		{name: "equivalent output directories", insertionName: "api/user_grpc.pb.go", insertionOut: "./gen"},
		{name: "duplicate producer is unambiguous", insertionName: "api/user_grpc.pb.go", insertionOut: "gen", duplicate: true},
		{name: "other output directory has no producer", insertionName: "api/user_grpc.pb.go", insertionOut: "other", wantError: "file not found (bucket)"},
		{name: "ambiguous original name is rejected", insertionName: "api/user_grpc.pb.go", insertionOut: "gen", ambiguous: true, wantError: "ambiguous insertion target"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			producer := &pluginpb.CodeGeneratorResponse_File{
				Name:    proto.String("api/user_grpc.pb.go"),
				Content: proto.String("// Code generated by custom. DO NOT EDIT.\n// source: api/user.proto\n\npackage userv1\n// @@protoc_insertion_point(example)\n"),
			}
			executor := &goOutputExecutor{responses: map[string]*pluginpb.CodeGeneratorResponse{
				"producer": {File: []*pluginpb.CodeGeneratorResponse_File{producer}},
				"insert": {File: []*pluginpb.CodeGeneratorResponse_File{{
					Name: proto.String(tt.insertionName), InsertionPoint: proto.String("example"), Content: proto.String("const Inserted = 1\n"),
				}}},
			}}
			plugins := []Plugin{{Source: PluginSource{Name: "producer"}, Out: "gen", Options: map[string][]string{"paths": {"source_relative"}}}}
			if tt.duplicate || tt.ambiguous {
				second := proto.Clone(producer).(*pluginpb.CodeGeneratorResponse_File)
				if tt.ambiguous {
					second.Content = proto.String("// Code generated by custom. DO NOT EDIT.\n// source: api/user_grpc.proto\n\npackage typesv1\n// @@protoc_insertion_point(example)\n")
				}
				executor.responses["second"] = &pluginpb.CodeGeneratorResponse{File: []*pluginpb.CodeGeneratorResponse_File{second}}
				plugins = append(plugins, Plugin{Source: PluginSource{Name: "second"}, Out: "gen", Options: map[string][]string{"paths": {"source_relative"}}})
			}
			insertion := Plugin{Source: PluginSource{Name: "insert"}, Out: tt.insertionOut, Options: tt.options}
			if !tt.separatePlans {
				plugins = append(plugins, insertion)
			}
			app := testCoreWithPlugins(plugins, executor)
			app.goPackageOutputPrefix = "example.test/generated"
			plan := &GenerationPlan{core: app, root: root,
				files: []string{"api/user.proto", "api/user_grpc.proto"},
				descriptors: []*descriptorpb.FileDescriptorProto{
					{Name: proto.String("api/user.proto"), Options: &descriptorpb.FileOptions{GoPackage: proto.String("example.test/generated/user/v1;userv1")}},
					{Name: proto.String("api/user_grpc.proto"), Options: &descriptorpb.FileOptions{GoPackage: proto.String("example.test/generated/types/v1;typesv1")}},
				},
			}
			bucket := NewGenerateBucket()

			err := plan.ExecuteInto(t.Context(), bucket)
			if tt.separatePlans {
				require.NoError(t, err)
				insertionPlan := &GenerationPlan{core: testCoreWithPlugins([]Plugin{insertion}, executor), root: root,
					files: plan.files, descriptors: plan.descriptors,
				}
				err = insertionPlan.ExecuteInto(t.Context(), bucket)
			}

			if tt.wantError != "" {
				require.ErrorContains(t, err, tt.wantError)
				return
			}
			require.NoError(t, err)
			file, ok := bucket.GetFile(t.Context(), filepath.Join(root, "gen/user/v1/user_grpc.pb.go"))
			require.True(t, ok)
			assert.Contains(t, string(file.Data()), "const Inserted = 1\n// @@protoc_insertion_point(example)")
			_, ok = bucket.GetFile(t.Context(), filepath.Join(root, "gen/types/v1/user_grpc.pb.go"))
			assert.False(t, ok)
		})
	}
}

func TestExecuteIntoGoImportMappingControlsOutputDirectory(t *testing.T) {
	t.Parallel()

	const prefix = "example.test/generated"
	tests := []struct {
		name    string
		prefix  string
		output  string
		options map[string][]string
		want    string
	}{
		{name: "mapping overrides descriptor", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + "/custom"}}, want: "custom/models.pb.go"},
		{name: "mapping package alias is not a directory", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + "/custom;alias"}}, want: "custom/models.pb.go"},
		{name: "last nonempty mapping wins", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + "/old", prefix + "/custom"}}, want: "custom/models.pb.go"},
		{name: "empty mapping keeps earlier import", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + "/custom", ""}}, want: "custom/models.pb.go"},
		{name: "alias only mapping keeps descriptor import", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {";alias"}}, want: "common/v1/models.pb.go"},
		{name: "alias only mapping keeps earlier import", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + "/custom", ";alias"}}, want: "custom/models.pb.go"},
		{name: "empty mapping keeps descriptor import", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {""}}, want: "common/v1/models.pb.go"},
		{name: "outside prefix keeps plugin path", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {"example.test/other/custom"}}, want: "api/models.pb.go"},
		{name: "SDK root mapping", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + ";sdk"}}, want: "models.pb.go"},
		{name: "marker uses effective mapping", prefix: prefix + "/{{file_path}}", options: map[string][]string{"paths": {"source_relative"}, "Mapi/models.proto": {prefix + "/custom"}}, want: "custom/models.pb.go"},
		{name: "last paths option is source relative", options: map[string][]string{"paths": {"import", "source_relative"}, "Mapi/models.proto": {prefix + "/custom"}}, want: "custom/models.pb.go"},
		{name: "last paths option is import", output: prefix + "/custom/models.pb.go", options: map[string][]string{"paths": {"source_relative", "import"}, "Mapi/models.proto": {prefix + "/custom"}}, want: prefix + "/custom/models.pb.go"},
		{name: "default import mode remains plugin controlled", output: prefix + "/custom/models.pb.go", options: map[string][]string{"Mapi/models.proto": {prefix + "/custom"}}, want: prefix + "/custom/models.pb.go"},
		{name: "module mode remains plugin controlled", output: "custom/models.pb.go", options: map[string][]string{"paths": {"import"}, "module": {prefix}, "Mapi/models.proto": {prefix + "/custom"}}, want: "custom/models.pb.go"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			output := tt.output
			if output == "" {
				output = "api/models.pb.go"
			}
			executor := &goOutputExecutor{responses: map[string]*pluginpb.CodeGeneratorResponse{
				"go-output": {File: []*pluginpb.CodeGeneratorResponse_File{{
					Name: proto.String(output), Content: proto.String("// Code generated by custom. DO NOT EDIT.\n// source: api/models.proto\n\npackage commonv1\n"),
				}}},
			}}
			app := testCoreWithPlugins([]Plugin{{Source: PluginSource{Name: "go-output"}, Out: "gen", Options: tt.options}}, executor)
			app.goPackageOutputPrefix = tt.prefix
			if app.goPackageOutputPrefix == "" {
				app.goPackageOutputPrefix = prefix
			}
			descriptor := &descriptorpb.FileDescriptorProto{
				Name: proto.String("api/models.proto"), Options: &descriptorpb.FileOptions{GoPackage: proto.String(prefix + "/common/v1;commonv1")},
			}
			plan := &GenerationPlan{core: app, root: root, files: []string{"api/models.proto"}, descriptors: []*descriptorpb.FileDescriptorProto{descriptor}}
			bucket := NewGenerateBucket()

			err := plan.ExecuteInto(t.Context(), bucket)

			require.NoError(t, err)
			_, ok := bucket.GetFile(t.Context(), filepath.Join(root, "gen", filepath.FromSlash(tt.want)))
			assert.True(t, ok, "expected generated file at %s", tt.want)
			assert.Equal(t, prefix+"/common/v1;commonv1", descriptor.GetOptions().GetGoPackage(), "plugin mappings must not mutate prepared descriptors")
		})
	}
}

func TestExecuteIntoConcurrentGoOutputMappings(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	bucket := NewGenerateBucket()
	responses := map[string]*pluginpb.CodeGeneratorResponse{
		"producer": {File: []*pluginpb.CodeGeneratorResponse_File{{
			Name: proto.String("api/models.pb.go"), Content: proto.String("// source: api/models.proto\npackage commonv1\n// @@protoc_insertion_point(example)\n"),
		}}},
		"insert": {File: []*pluginpb.CodeGeneratorResponse_File{{
			Name: proto.String("api/models.pb.go"), InsertionPoint: proto.String("example"), Content: proto.String("const Inserted = 1\n"),
		}}},
	}
	var group sync.WaitGroup
	for i := range 16 {
		group.Go(func() {
			out := fmt.Sprintf("gen/client%d", i)
			executor := &goOutputExecutor{responses: responses}
			app := testCoreWithPlugins([]Plugin{
				{Source: PluginSource{Name: "producer"}, Out: out, Options: map[string][]string{"paths": {"source_relative"}}},
				{Source: PluginSource{Name: "insert"}, Out: out},
			}, executor)
			app.goPackageOutputPrefix = "example.test/generated"
			plan := &GenerationPlan{core: app, root: root, files: []string{"api/models.proto"},
				descriptors: []*descriptorpb.FileDescriptorProto{{Name: proto.String("api/models.proto"), Options: &descriptorpb.FileOptions{GoPackage: proto.String("example.test/generated/common/v1;commonv1")}}},
			}

			assert.NoError(t, plan.ExecuteInto(t.Context(), bucket))
		})
	}
	group.Wait()
	for i := range 16 {
		file, ok := bucket.GetFile(t.Context(), filepath.Join(root, fmt.Sprintf("gen/client%d/common/v1/models.pb.go", i)))
		require.True(t, ok)
		assert.Contains(t, string(file.Data()), "const Inserted = 1\n// @@protoc_insertion_point(example)")
	}
}
