package core

import (
	"path/filepath"
	"strings"

	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

// goPackageOutputDirs uses the final descriptor options and the plugin's import
// mappings. Packages outside the prefix keep their plugin paths.
func goPackageOutputDirs(prefix string, files []string, descriptors []*descriptorpb.FileDescriptorProto, options map[string][]string) map[string]string {
	if template, _, marker := strings.Cut(prefix, "{{"); marker {
		separator := strings.LastIndex(template, "/")
		if separator < 0 {
			return nil
		}
		prefix = template[:separator]
	}
	prefix = strings.TrimRight(prefix, "/")
	if prefix == "" {
		return nil
	}
	targets := make(map[string]bool, len(files))
	for _, file := range files {
		targets[file] = true
	}
	directories := make(map[string]string)
	for _, descriptor := range descriptors {
		if !targets[descriptor.GetName()] {
			continue
		}
		importPath, _, _ := strings.Cut(descriptor.GetOptions().GetGoPackage(), ";")
		// protogen keeps the last nonempty M import path. Alias-only and empty
		// mappings leave a previous mapping or the descriptor import in place.
		for _, mapping := range options["M"+descriptor.GetName()] {
			if mappedImport, _, _ := strings.Cut(mapping, ";"); mappedImport != "" {
				importPath = mappedImport
			}
		}
		if importPath == prefix {
			directories[descriptor.GetName()] = "."
			continue
		}
		if directory, ok := strings.CutPrefix(importPath, prefix+"/"); ok {
			directories[descriptor.GetName()] = directory
		}
	}
	return directories
}

func goPackageOutputPath(file *pluginpb.CodeGeneratorResponse_File, directories map[string]string) string {
	name := file.GetName()
	if len(directories) == 0 || !strings.HasSuffix(name, ".go") {
		return name
	}
	// Go and Go gRPC headers disambiguate user_grpc.proto from the gRPC
	// companion of user.proto. Plugins without that header use the longest basename.
	declaredSource := goPackageOutputSource(file.GetContent())
	outputDir := filepath.ToSlash(filepath.Dir(name))
	outputBase := filepath.Base(name)
	longestBase := ""
	output := name
	for source, directory := range directories {
		if declaredSource != "" && source != declaredSource {
			continue
		}
		if outputDir != filepath.ToSlash(filepath.Dir(source)) {
			continue
		}
		base := strings.TrimSuffix(filepath.Base(source), ".proto")
		if !strings.HasPrefix(outputBase, base+".") && !strings.HasPrefix(outputBase, base+"_") {
			continue
		}
		if len(base) > len(longestBase) {
			longestBase = base
			output = filepath.ToSlash(filepath.Join(directory, outputBase))
		}
	}
	return output
}

func goPackageOutputSource(content string) string {
	// Go plugins copy proto comments that may themselves contain a generated
	// marker. Prefer their versioned header before falling back to older headers.
	if source, ok := goPackageOutputProtocSource(content); ok {
		return source
	}

	var sourceOnly string
	generatedHeader := false
	for line := range strings.Lines(content) {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "package ") {
			break
		}
		if strings.HasPrefix(line, "// Code generated ") && strings.HasSuffix(line, " DO NOT EDIT.") {
			generatedHeader = true
			continue
		}
		// The generator header is one comment block. Detached source or package
		// comments may contain source lines before and after this block.
		if generatedHeader && !strings.HasPrefix(line, "//") {
			break
		}
		if source, ok := strings.CutPrefix(line, "// source: "); ok {
			if generatedHeader {
				return strings.TrimSpace(source)
			}
			if sourceOnly == "" {
				sourceOnly = strings.TrimSpace(source)
			}
		}
	}
	if generatedHeader {
		return ""
	}
	// Retain source-only headers used by plugins without a generated marker.
	return sourceOnly
}

func goPackageOutputProtocSource(content string) (string, bool) {
	type header struct {
		generator string
		comments  []string
	}
	var headers []header
	currentHeader := -1
	for line := range strings.Lines(content) {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "package ") {
			break
		}
		var generator string
		switch line {
		case "// Code generated by protoc-gen-go. DO NOT EDIT.":
			generator = "protoc-gen-go"
		case "// Code generated by protoc-gen-go-grpc. DO NOT EDIT.":
			generator = "protoc-gen-go-grpc"
		}
		if generator != "" {
			headers = append(headers, header{generator: generator})
			currentHeader = len(headers) - 1
			continue
		}
		if currentHeader < 0 {
			continue
		}
		// End at the first block boundary even when the header has no source.
		// Package comments following it belong to the proto author.
		if !strings.HasPrefix(line, "//") {
			currentHeader = -1
			continue
		}
		headers[currentHeader].comments = append(headers[currentHeader].comments, line)
	}

	var fallbackSource string
	for i, header := range headers {
		var source string
		for _, line := range header.comments {
			if declaredSource, ok := strings.CutPrefix(line, "// source: "); ok {
				source = strings.TrimSpace(declaredSource)
				break
			}
		}
		if i == 0 {
			fallbackSource = source
		}
		// Both pinned Go generators put the versions label, generator version,
		// and protoc version immediately after their marker. A copied marker
		// alone does not have this structure. Prefer the first complete header
		// so later package comments cannot replace its source.
		if len(header.comments) >= 3 && header.comments[0] == "// versions:" &&
			goPackageOutputVersionRow(header.comments[1], header.generator) &&
			goPackageOutputVersionRow(header.comments[2], "protoc") {
			return source, true
		}
	}
	return fallbackSource, len(headers) > 0
}

func goPackageOutputVersionRow(line, generator string) bool {
	fields := strings.Fields(strings.TrimPrefix(line, "//"))
	if len(fields) > 0 && fields[0] == "-" {
		fields = fields[1:]
	}
	if len(fields) != 2 || fields[0] != generator {
		return false
	}
	version := fields[1]
	return version == "(unknown)" || len(version) > 1 && version[0] == 'v' && version[1] >= '0' && version[1] <= '9'
}
