// Code generated by mockery. DO NOT EDIT.

package core

import (
	iter "iter"

	models "github.com/easyp-tech/easyp/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// LockFileMock is an autogenerated mock type for the LockFile type
type LockFileMock struct {
	mock.Mock
}

type LockFileMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LockFileMock) EXPECT() *LockFileMock_Expecter {
	return &LockFileMock_Expecter{mock: &_m.Mock}
}

// DepsIter provides a mock function with no fields
func (_m *LockFileMock) DepsIter() iter.Seq[models.LockFileInfo] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DepsIter")
	}

	var r0 iter.Seq[models.LockFileInfo]
	if rf, ok := ret.Get(0).(func() iter.Seq[models.LockFileInfo]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[models.LockFileInfo])
		}
	}

	return r0
}

// LockFileMock_DepsIter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepsIter'
type LockFileMock_DepsIter_Call struct {
	*mock.Call
}

// DepsIter is a helper method to define mock.On call
func (_e *LockFileMock_Expecter) DepsIter() *LockFileMock_DepsIter_Call {
	return &LockFileMock_DepsIter_Call{Call: _e.mock.On("DepsIter")}
}

func (_c *LockFileMock_DepsIter_Call) Run(run func()) *LockFileMock_DepsIter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LockFileMock_DepsIter_Call) Return(_a0 iter.Seq[models.LockFileInfo]) *LockFileMock_DepsIter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LockFileMock_DepsIter_Call) RunAndReturn(run func() iter.Seq[models.LockFileInfo]) *LockFileMock_DepsIter_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmpty provides a mock function with no fields
func (_m *LockFileMock) IsEmpty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LockFileMock_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type LockFileMock_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
func (_e *LockFileMock_Expecter) IsEmpty() *LockFileMock_IsEmpty_Call {
	return &LockFileMock_IsEmpty_Call{Call: _e.mock.On("IsEmpty")}
}

func (_c *LockFileMock_IsEmpty_Call) Run(run func()) *LockFileMock_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LockFileMock_IsEmpty_Call) Return(_a0 bool) *LockFileMock_IsEmpty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LockFileMock_IsEmpty_Call) RunAndReturn(run func() bool) *LockFileMock_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: moduleName
func (_m *LockFileMock) Read(moduleName string) (models.LockFileInfo, error) {
	ret := _m.Called(moduleName)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 models.LockFileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.LockFileInfo, error)); ok {
		return rf(moduleName)
	}
	if rf, ok := ret.Get(0).(func(string) models.LockFileInfo); ok {
		r0 = rf(moduleName)
	} else {
		r0 = ret.Get(0).(models.LockFileInfo)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(moduleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockFileMock_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type LockFileMock_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - moduleName string
func (_e *LockFileMock_Expecter) Read(moduleName interface{}) *LockFileMock_Read_Call {
	return &LockFileMock_Read_Call{Call: _e.mock.On("Read", moduleName)}
}

func (_c *LockFileMock_Read_Call) Run(run func(moduleName string)) *LockFileMock_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LockFileMock_Read_Call) Return(_a0 models.LockFileInfo, _a1 error) *LockFileMock_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LockFileMock_Read_Call) RunAndReturn(run func(string) (models.LockFileInfo, error)) *LockFileMock_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: moduleName, revisionVersion, installedPackageHash
func (_m *LockFileMock) Write(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) error {
	ret := _m.Called(moduleName, revisionVersion, installedPackageHash)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, models.ModuleHash) error); ok {
		r0 = rf(moduleName, revisionVersion, installedPackageHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LockFileMock_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type LockFileMock_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - moduleName string
//   - revisionVersion string
//   - installedPackageHash models.ModuleHash
func (_e *LockFileMock_Expecter) Write(moduleName interface{}, revisionVersion interface{}, installedPackageHash interface{}) *LockFileMock_Write_Call {
	return &LockFileMock_Write_Call{Call: _e.mock.On("Write", moduleName, revisionVersion, installedPackageHash)}
}

func (_c *LockFileMock_Write_Call) Run(run func(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash)) *LockFileMock_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(models.ModuleHash))
	})
	return _c
}

func (_c *LockFileMock_Write_Call) Return(_a0 error) *LockFileMock_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LockFileMock_Write_Call) RunAndReturn(run func(string, string, models.ModuleHash) error) *LockFileMock_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewLockFileMock creates a new instance of LockFileMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLockFileMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LockFileMock {
	mock := &LockFileMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
