// Code generated by mockery. DO NOT EDIT.

package core

import (
	context "context"

	models "github.com/easyp-tech/easyp/internal/core/models"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

type StorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageMock) EXPECT() *StorageMock_Expecter {
	return &StorageMock_Expecter{mock: &_m.Mock}
}

// CreateCacheDownloadDir provides a mock function with given fields: _a0
func (_m *StorageMock) CreateCacheDownloadDir(_a0 models.CacheDownloadPaths) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateCacheDownloadDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.CacheDownloadPaths) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_CreateCacheDownloadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCacheDownloadDir'
type StorageMock_CreateCacheDownloadDir_Call struct {
	*mock.Call
}

// CreateCacheDownloadDir is a helper method to define mock.On call
//   - _a0 models.CacheDownloadPaths
func (_e *StorageMock_Expecter) CreateCacheDownloadDir(_a0 interface{}) *StorageMock_CreateCacheDownloadDir_Call {
	return &StorageMock_CreateCacheDownloadDir_Call{Call: _e.mock.On("CreateCacheDownloadDir", _a0)}
}

func (_c *StorageMock_CreateCacheDownloadDir_Call) Run(run func(_a0 models.CacheDownloadPaths)) *StorageMock_CreateCacheDownloadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.CacheDownloadPaths))
	})
	return _c
}

func (_c *StorageMock_CreateCacheDownloadDir_Call) Return(_a0 error) *StorageMock_CreateCacheDownloadDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_CreateCacheDownloadDir_Call) RunAndReturn(run func(models.CacheDownloadPaths) error) *StorageMock_CreateCacheDownloadDir_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCacheRepositoryDir provides a mock function with given fields: name
func (_m *StorageMock) CreateCacheRepositoryDir(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateCacheRepositoryDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_CreateCacheRepositoryDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCacheRepositoryDir'
type StorageMock_CreateCacheRepositoryDir_Call struct {
	*mock.Call
}

// CreateCacheRepositoryDir is a helper method to define mock.On call
//   - name string
func (_e *StorageMock_Expecter) CreateCacheRepositoryDir(name interface{}) *StorageMock_CreateCacheRepositoryDir_Call {
	return &StorageMock_CreateCacheRepositoryDir_Call{Call: _e.mock.On("CreateCacheRepositoryDir", name)}
}

func (_c *StorageMock_CreateCacheRepositoryDir_Call) Run(run func(name string)) *StorageMock_CreateCacheRepositoryDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *StorageMock_CreateCacheRepositoryDir_Call) Return(_a0 string, _a1 error) *StorageMock_CreateCacheRepositoryDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_CreateCacheRepositoryDir_Call) RunAndReturn(run func(string) (string, error)) *StorageMock_CreateCacheRepositoryDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheDownloadPaths provides a mock function with given fields: moduleName, version
func (_m *StorageMock) GetCacheDownloadPaths(moduleName string, version string) models.CacheDownloadPaths {
	ret := _m.Called(moduleName, version)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheDownloadPaths")
	}

	var r0 models.CacheDownloadPaths
	if rf, ok := ret.Get(0).(func(string, string) models.CacheDownloadPaths); ok {
		r0 = rf(moduleName, version)
	} else {
		r0 = ret.Get(0).(models.CacheDownloadPaths)
	}

	return r0
}

// StorageMock_GetCacheDownloadPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheDownloadPaths'
type StorageMock_GetCacheDownloadPaths_Call struct {
	*mock.Call
}

// GetCacheDownloadPaths is a helper method to define mock.On call
//   - moduleName string
//   - version string
func (_e *StorageMock_Expecter) GetCacheDownloadPaths(moduleName interface{}, version interface{}) *StorageMock_GetCacheDownloadPaths_Call {
	return &StorageMock_GetCacheDownloadPaths_Call{Call: _e.mock.On("GetCacheDownloadPaths", moduleName, version)}
}

func (_c *StorageMock_GetCacheDownloadPaths_Call) Run(run func(moduleName string, version string)) *StorageMock_GetCacheDownloadPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *StorageMock_GetCacheDownloadPaths_Call) Return(_a0 models.CacheDownloadPaths) *StorageMock_GetCacheDownloadPaths_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_GetCacheDownloadPaths_Call) RunAndReturn(run func(string, string) models.CacheDownloadPaths) *StorageMock_GetCacheDownloadPaths_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstallDir provides a mock function with given fields: moduleName, revisionVersion
func (_m *StorageMock) GetInstallDir(moduleName string, revisionVersion string) string {
	ret := _m.Called(moduleName, revisionVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetInstallDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(moduleName, revisionVersion)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// StorageMock_GetInstallDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstallDir'
type StorageMock_GetInstallDir_Call struct {
	*mock.Call
}

// GetInstallDir is a helper method to define mock.On call
//   - moduleName string
//   - revisionVersion string
func (_e *StorageMock_Expecter) GetInstallDir(moduleName interface{}, revisionVersion interface{}) *StorageMock_GetInstallDir_Call {
	return &StorageMock_GetInstallDir_Call{Call: _e.mock.On("GetInstallDir", moduleName, revisionVersion)}
}

func (_c *StorageMock_GetInstallDir_Call) Run(run func(moduleName string, revisionVersion string)) *StorageMock_GetInstallDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *StorageMock_GetInstallDir_Call) Return(_a0 string) *StorageMock_GetInstallDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_GetInstallDir_Call) RunAndReturn(run func(string, string) string) *StorageMock_GetInstallDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetInstalledModuleHash provides a mock function with given fields: moduleName, revisionVersion
func (_m *StorageMock) GetInstalledModuleHash(moduleName string, revisionVersion string) (models.ModuleHash, error) {
	ret := _m.Called(moduleName, revisionVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetInstalledModuleHash")
	}

	var r0 models.ModuleHash
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (models.ModuleHash, error)); ok {
		return rf(moduleName, revisionVersion)
	}
	if rf, ok := ret.Get(0).(func(string, string) models.ModuleHash); ok {
		r0 = rf(moduleName, revisionVersion)
	} else {
		r0 = ret.Get(0).(models.ModuleHash)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(moduleName, revisionVersion)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_GetInstalledModuleHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInstalledModuleHash'
type StorageMock_GetInstalledModuleHash_Call struct {
	*mock.Call
}

// GetInstalledModuleHash is a helper method to define mock.On call
//   - moduleName string
//   - revisionVersion string
func (_e *StorageMock_Expecter) GetInstalledModuleHash(moduleName interface{}, revisionVersion interface{}) *StorageMock_GetInstalledModuleHash_Call {
	return &StorageMock_GetInstalledModuleHash_Call{Call: _e.mock.On("GetInstalledModuleHash", moduleName, revisionVersion)}
}

func (_c *StorageMock_GetInstalledModuleHash_Call) Run(run func(moduleName string, revisionVersion string)) *StorageMock_GetInstalledModuleHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *StorageMock_GetInstalledModuleHash_Call) Return(_a0 models.ModuleHash, _a1 error) *StorageMock_GetInstalledModuleHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_GetInstalledModuleHash_Call) RunAndReturn(run func(string, string) (models.ModuleHash, error)) *StorageMock_GetInstalledModuleHash_Call {
	_c.Call.Return(run)
	return _c
}

// Install provides a mock function with given fields: ctx, cacheDownloadPaths, module, revision, moduleConfig
func (_m *StorageMock) Install(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig) (models.ModuleHash, error) {
	ret := _m.Called(ctx, cacheDownloadPaths, module, revision, moduleConfig)

	if len(ret) == 0 {
		panic("no return value specified for Install")
	}

	var r0 models.ModuleHash
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CacheDownloadPaths, models.Module, models.Revision, models.ModuleConfig) (models.ModuleHash, error)); ok {
		return rf(ctx, cacheDownloadPaths, module, revision, moduleConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CacheDownloadPaths, models.Module, models.Revision, models.ModuleConfig) models.ModuleHash); ok {
		r0 = rf(ctx, cacheDownloadPaths, module, revision, moduleConfig)
	} else {
		r0 = ret.Get(0).(models.ModuleHash)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CacheDownloadPaths, models.Module, models.Revision, models.ModuleConfig) error); ok {
		r1 = rf(ctx, cacheDownloadPaths, module, revision, moduleConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_Install_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Install'
type StorageMock_Install_Call struct {
	*mock.Call
}

// Install is a helper method to define mock.On call
//   - ctx context.Context
//   - cacheDownloadPaths models.CacheDownloadPaths
//   - module models.Module
//   - revision models.Revision
//   - moduleConfig models.ModuleConfig
func (_e *StorageMock_Expecter) Install(ctx interface{}, cacheDownloadPaths interface{}, module interface{}, revision interface{}, moduleConfig interface{}) *StorageMock_Install_Call {
	return &StorageMock_Install_Call{Call: _e.mock.On("Install", ctx, cacheDownloadPaths, module, revision, moduleConfig)}
}

func (_c *StorageMock_Install_Call) Run(run func(ctx context.Context, cacheDownloadPaths models.CacheDownloadPaths, module models.Module, revision models.Revision, moduleConfig models.ModuleConfig)) *StorageMock_Install_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CacheDownloadPaths), args[2].(models.Module), args[3].(models.Revision), args[4].(models.ModuleConfig))
	})
	return _c
}

func (_c *StorageMock_Install_Call) Return(_a0 models.ModuleHash, _a1 error) *StorageMock_Install_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_Install_Call) RunAndReturn(run func(context.Context, models.CacheDownloadPaths, models.Module, models.Revision, models.ModuleConfig) (models.ModuleHash, error)) *StorageMock_Install_Call {
	_c.Call.Return(run)
	return _c
}

// ReadInstalledModuleInfo provides a mock function with given fields: cacheDownloadPaths
func (_m *StorageMock) ReadInstalledModuleInfo(cacheDownloadPaths models.CacheDownloadPaths) (models.InstalledModuleInfo, error) {
	ret := _m.Called(cacheDownloadPaths)

	if len(ret) == 0 {
		panic("no return value specified for ReadInstalledModuleInfo")
	}

	var r0 models.InstalledModuleInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(models.CacheDownloadPaths) (models.InstalledModuleInfo, error)); ok {
		return rf(cacheDownloadPaths)
	}
	if rf, ok := ret.Get(0).(func(models.CacheDownloadPaths) models.InstalledModuleInfo); ok {
		r0 = rf(cacheDownloadPaths)
	} else {
		r0 = ret.Get(0).(models.InstalledModuleInfo)
	}

	if rf, ok := ret.Get(1).(func(models.CacheDownloadPaths) error); ok {
		r1 = rf(cacheDownloadPaths)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_ReadInstalledModuleInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadInstalledModuleInfo'
type StorageMock_ReadInstalledModuleInfo_Call struct {
	*mock.Call
}

// ReadInstalledModuleInfo is a helper method to define mock.On call
//   - cacheDownloadPaths models.CacheDownloadPaths
func (_e *StorageMock_Expecter) ReadInstalledModuleInfo(cacheDownloadPaths interface{}) *StorageMock_ReadInstalledModuleInfo_Call {
	return &StorageMock_ReadInstalledModuleInfo_Call{Call: _e.mock.On("ReadInstalledModuleInfo", cacheDownloadPaths)}
}

func (_c *StorageMock_ReadInstalledModuleInfo_Call) Run(run func(cacheDownloadPaths models.CacheDownloadPaths)) *StorageMock_ReadInstalledModuleInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.CacheDownloadPaths))
	})
	return _c
}

func (_c *StorageMock_ReadInstalledModuleInfo_Call) Return(_a0 models.InstalledModuleInfo, _a1 error) *StorageMock_ReadInstalledModuleInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_ReadInstalledModuleInfo_Call) RunAndReturn(run func(models.CacheDownloadPaths) (models.InstalledModuleInfo, error)) *StorageMock_ReadInstalledModuleInfo_Call {
	_c.Call.Return(run)
	return _c
}

// WriteInstalledModuleInfo provides a mock function with given fields: cacheDownloadPaths, installedModuleInfo
func (_m *StorageMock) WriteInstalledModuleInfo(cacheDownloadPaths models.CacheDownloadPaths, installedModuleInfo models.InstalledModuleInfo) error {
	ret := _m.Called(cacheDownloadPaths, installedModuleInfo)

	if len(ret) == 0 {
		panic("no return value specified for WriteInstalledModuleInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.CacheDownloadPaths, models.InstalledModuleInfo) error); ok {
		r0 = rf(cacheDownloadPaths, installedModuleInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_WriteInstalledModuleInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteInstalledModuleInfo'
type StorageMock_WriteInstalledModuleInfo_Call struct {
	*mock.Call
}

// WriteInstalledModuleInfo is a helper method to define mock.On call
//   - cacheDownloadPaths models.CacheDownloadPaths
//   - installedModuleInfo models.InstalledModuleInfo
func (_e *StorageMock_Expecter) WriteInstalledModuleInfo(cacheDownloadPaths interface{}, installedModuleInfo interface{}) *StorageMock_WriteInstalledModuleInfo_Call {
	return &StorageMock_WriteInstalledModuleInfo_Call{Call: _e.mock.On("WriteInstalledModuleInfo", cacheDownloadPaths, installedModuleInfo)}
}

func (_c *StorageMock_WriteInstalledModuleInfo_Call) Run(run func(cacheDownloadPaths models.CacheDownloadPaths, installedModuleInfo models.InstalledModuleInfo)) *StorageMock_WriteInstalledModuleInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.CacheDownloadPaths), args[1].(models.InstalledModuleInfo))
	})
	return _c
}

func (_c *StorageMock_WriteInstalledModuleInfo_Call) Return(_a0 error) *StorageMock_WriteInstalledModuleInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_WriteInstalledModuleInfo_Call) RunAndReturn(run func(models.CacheDownloadPaths, models.InstalledModuleInfo) error) *StorageMock_WriteInstalledModuleInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
