// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	iter "iter"

	mock "github.com/stretchr/testify/mock"

	models "github.com/easyp-tech/easyp/internal/mod/models"
)

// LockFile is an autogenerated mock type for the LockFile type
type LockFile struct {
	mock.Mock
}

type LockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *LockFile) EXPECT() *LockFile_Expecter {
	return &LockFile_Expecter{mock: &_m.Mock}
}

// DepsIter provides a mock function with given fields:
func (_m *LockFile) DepsIter() iter.Seq[models.LockFileInfo] {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DepsIter")
	}

	var r0 iter.Seq[models.LockFileInfo]
	if rf, ok := ret.Get(0).(func() iter.Seq[models.LockFileInfo]); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(iter.Seq[models.LockFileInfo])
		}
	}

	return r0
}

// LockFile_DepsIter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DepsIter'
type LockFile_DepsIter_Call struct {
	*mock.Call
}

// DepsIter is a helper method to define mock.On call
func (_e *LockFile_Expecter) DepsIter() *LockFile_DepsIter_Call {
	return &LockFile_DepsIter_Call{Call: _e.mock.On("DepsIter")}
}

func (_c *LockFile_DepsIter_Call) Run(run func()) *LockFile_DepsIter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LockFile_DepsIter_Call) Return(_a0 iter.Seq[models.LockFileInfo]) *LockFile_DepsIter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LockFile_DepsIter_Call) RunAndReturn(run func() iter.Seq[models.LockFileInfo]) *LockFile_DepsIter_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmpty provides a mock function with given fields:
func (_m *LockFile) IsEmpty() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LockFile_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type LockFile_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
func (_e *LockFile_Expecter) IsEmpty() *LockFile_IsEmpty_Call {
	return &LockFile_IsEmpty_Call{Call: _e.mock.On("IsEmpty")}
}

func (_c *LockFile_IsEmpty_Call) Run(run func()) *LockFile_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LockFile_IsEmpty_Call) Return(_a0 bool) *LockFile_IsEmpty_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LockFile_IsEmpty_Call) RunAndReturn(run func() bool) *LockFile_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: moduleName
func (_m *LockFile) Read(moduleName string) (models.LockFileInfo, error) {
	ret := _m.Called(moduleName)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 models.LockFileInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.LockFileInfo, error)); ok {
		return rf(moduleName)
	}
	if rf, ok := ret.Get(0).(func(string) models.LockFileInfo); ok {
		r0 = rf(moduleName)
	} else {
		r0 = ret.Get(0).(models.LockFileInfo)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(moduleName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LockFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type LockFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - moduleName string
func (_e *LockFile_Expecter) Read(moduleName interface{}) *LockFile_Read_Call {
	return &LockFile_Read_Call{Call: _e.mock.On("Read", moduleName)}
}

func (_c *LockFile_Read_Call) Run(run func(moduleName string)) *LockFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LockFile_Read_Call) Return(_a0 models.LockFileInfo, _a1 error) *LockFile_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LockFile_Read_Call) RunAndReturn(run func(string) (models.LockFileInfo, error)) *LockFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: moduleName, revisionVersion, installedPackageHash
func (_m *LockFile) Write(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash) error {
	ret := _m.Called(moduleName, revisionVersion, installedPackageHash)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, models.ModuleHash) error); ok {
		r0 = rf(moduleName, revisionVersion, installedPackageHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LockFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type LockFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - moduleName string
//   - revisionVersion string
//   - installedPackageHash models.ModuleHash
func (_e *LockFile_Expecter) Write(moduleName interface{}, revisionVersion interface{}, installedPackageHash interface{}) *LockFile_Write_Call {
	return &LockFile_Write_Call{Call: _e.mock.On("Write", moduleName, revisionVersion, installedPackageHash)}
}

func (_c *LockFile_Write_Call) Run(run func(moduleName string, revisionVersion string, installedPackageHash models.ModuleHash)) *LockFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(models.ModuleHash))
	})
	return _c
}

func (_c *LockFile_Write_Call) Return(_a0 error) *LockFile_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LockFile_Write_Call) RunAndReturn(run func(string, string, models.ModuleHash) error) *LockFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewLockFile creates a new instance of LockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *LockFile {
	mock := &LockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
