package config

import (
	"fmt"
	"slices"
)

// BreakingProfile describes one selectable producer-side compatibility profile.
type BreakingProfile struct {
	Name        string
	Description string
	Rules       []string
}

var breakingProfiles = []BreakingProfile{
	{
		Name:        "FILE",
		Description: "Generated source compatibility, including declaration file identity and moves.",
		Rules: []string{
			"MESSAGE_SAME_MESSAGE_SET_WIRE_FORMAT", "EXTENSION_SAME_NUMBER", "EXTENSION_SAME_EXTENDEE", "EXTENSION_MOVED", "FILE_SAME_PHP_CLASS_PREFIX",
			"FILE_NO_DELETE", "MESSAGE_MOVED", "ENUM_MOVED", "SERVICE_MOVED", "ONEOF_MOVED", "FILE_SAME_PACKAGE", "FILE_SAME_SYNTAX", "FILE_SAME_GO_PACKAGE", "FILE_SAME_JAVA_PACKAGE",
			"FILE_SAME_JAVA_OUTER_CLASSNAME", "FILE_SAME_JAVA_MULTIPLE_FILES", "FILE_SAME_JAVA_STRING_CHECK_UTF8",
			"FILE_SAME_CSHARP_NAMESPACE", "FILE_SAME_OBJC_CLASS_PREFIX", "FILE_SAME_OPTIMIZE_FOR", "FILE_SAME_PHP_NAMESPACE",
			"FILE_SAME_PHP_METADATA_NAMESPACE", "FILE_SAME_RUBY_PACKAGE", "FILE_SAME_SWIFT_PREFIX", "FILE_SAME_CC_ENABLE_ARENAS",
			"FILE_SAME_CC_GENERIC_SERVICES", "FILE_SAME_JAVA_GENERIC_SERVICES", "FILE_SAME_PY_GENERIC_SERVICES",
			"PACKAGE_NO_DELETE", "MESSAGE_NO_DELETE", "ENUM_NO_DELETE", "SERVICE_NO_DELETE", "RPC_NO_DELETE", "ONEOF_NO_DELETE",
			"FIELD_NO_DELETE", "FIELD_SAME_NAME", "FIELD_SAME_TYPE", "FIELD_SAME_CARDINALITY", "FIELD_SAME_JSON_NAME",
			"FIELD_SAME_ONEOF", "FIELD_SAME_DEFAULT", "FIELD_SAME_JSTYPE", "FIELD_SAME_CPP_STRING_TYPE",
			"FIELD_SAME_JAVA_UTF8_VALIDATION", "FIELD_SAME_UTF8_VALIDATION", "MESSAGE_NO_REMOVE_STANDARD_DESCRIPTOR_ACCESSOR",
			"MESSAGE_SAME_JSON_FORMAT", "ENUM_SAME_JSON_FORMAT", "ENUM_SAME_TYPE", "ENUM_VALUE_NO_DELETE", "ENUM_VALUE_SAME_NAME",
			"EXTENSION_NO_DELETE", "EXTENSION_MESSAGE_NO_DELETE", "RESERVED_MESSAGE_NO_DELETE", "RESERVED_ENUM_NO_DELETE",
			"MESSAGE_SAME_REQUIRED_FIELDS", "RPC_SAME_REQUEST_TYPE", "RPC_SAME_RESPONSE_TYPE", "RPC_SAME_CLIENT_STREAMING",
			"RPC_SAME_SERVER_STREAMING", "RPC_SAME_IDEMPOTENCY_LEVEL",
		},
	},
	{
		Name:        "PACKAGE",
		Description: "Generated source compatibility by protobuf package; declarations may move between files in that package.",
		Rules: []string{
			"MESSAGE_SAME_MESSAGE_SET_WIRE_FORMAT", "EXTENSION_SAME_NUMBER", "EXTENSION_SAME_EXTENDEE", "FILE_SAME_PHP_CLASS_PREFIX",
			"FILE_SAME_PACKAGE", "FILE_SAME_SYNTAX", "FILE_SAME_GO_PACKAGE", "FILE_SAME_JAVA_PACKAGE", "FILE_SAME_JAVA_OUTER_CLASSNAME",
			"FILE_SAME_JAVA_MULTIPLE_FILES", "FILE_SAME_JAVA_STRING_CHECK_UTF8", "FILE_SAME_CSHARP_NAMESPACE", "FILE_SAME_OBJC_CLASS_PREFIX",
			"FILE_SAME_OPTIMIZE_FOR", "FILE_SAME_PHP_NAMESPACE", "FILE_SAME_PHP_METADATA_NAMESPACE", "FILE_SAME_RUBY_PACKAGE",
			"FILE_SAME_SWIFT_PREFIX", "FILE_SAME_CC_ENABLE_ARENAS", "FILE_SAME_CC_GENERIC_SERVICES", "FILE_SAME_JAVA_GENERIC_SERVICES",
			"FILE_SAME_PY_GENERIC_SERVICES", "PACKAGE_NO_DELETE", "MESSAGE_NO_DELETE", "ENUM_NO_DELETE", "SERVICE_NO_DELETE", "RPC_NO_DELETE",
			"ONEOF_NO_DELETE", "FIELD_NO_DELETE", "FIELD_SAME_NAME", "FIELD_SAME_TYPE", "FIELD_SAME_CARDINALITY", "FIELD_SAME_JSON_NAME",
			"FIELD_SAME_ONEOF", "FIELD_SAME_DEFAULT", "FIELD_SAME_JSTYPE", "FIELD_SAME_CPP_STRING_TYPE", "FIELD_SAME_JAVA_UTF8_VALIDATION",
			"FIELD_SAME_UTF8_VALIDATION", "MESSAGE_NO_REMOVE_STANDARD_DESCRIPTOR_ACCESSOR", "MESSAGE_SAME_JSON_FORMAT", "ENUM_SAME_JSON_FORMAT",
			"ENUM_SAME_TYPE", "ENUM_VALUE_NO_DELETE", "ENUM_VALUE_SAME_NAME", "EXTENSION_NO_DELETE", "EXTENSION_MESSAGE_NO_DELETE",
			"RESERVED_MESSAGE_NO_DELETE", "RESERVED_ENUM_NO_DELETE", "MESSAGE_SAME_REQUIRED_FIELDS", "RPC_SAME_REQUEST_TYPE",
			"RPC_SAME_RESPONSE_TYPE", "RPC_SAME_CLIENT_STREAMING", "RPC_SAME_SERVER_STREAMING", "RPC_SAME_IDEMPOTENCY_LEVEL",
		},
	},
	{
		Name:        "WIRE_JSON",
		Description: "Binary and protobuf JSON compatibility, including reserved field and enum names.",
		Rules: []string{
			"SERVICE_NO_DELETE", "MESSAGE_SAME_MESSAGE_SET_WIRE_FORMAT", "EXTENSION_SAME_NUMBER", "EXTENSION_SAME_EXTENDEE",
			"FILE_SAME_PACKAGE", "FIELD_NO_DELETE_UNLESS_NAME_RESERVED", "FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED", "FIELD_SAME_NAME",
			"FIELD_SAME_JSON_NAME", "FIELD_WIRE_JSON_COMPATIBLE_TYPE", "FIELD_WIRE_JSON_COMPATIBLE_CARDINALITY", "FIELD_SAME_ONEOF",
			"FIELD_SAME_DEFAULT", "ENUM_VALUE_NO_DELETE_UNLESS_NAME_RESERVED", "ENUM_VALUE_NO_DELETE_UNLESS_NUMBER_RESERVED",
			"ENUM_VALUE_SAME_NAME", "MESSAGE_SAME_REQUIRED_FIELDS", "MESSAGE_SAME_JSON_FORMAT", "ENUM_SAME_JSON_FORMAT",
			"RESERVED_MESSAGE_NO_DELETE", "RESERVED_ENUM_NO_DELETE", "RPC_NO_DELETE", "RPC_SAME_REQUEST_TYPE", "RPC_SAME_RESPONSE_TYPE",
			"RPC_SAME_CLIENT_STREAMING", "RPC_SAME_SERVER_STREAMING", "RPC_SAME_IDEMPOTENCY_LEVEL",
		},
	},
	{
		Name:        "WIRE",
		Description: "Binary protobuf compatibility, including reserved field and enum numbers.",
		Rules: []string{
			"SERVICE_NO_DELETE", "MESSAGE_SAME_MESSAGE_SET_WIRE_FORMAT", "EXTENSION_SAME_NUMBER", "EXTENSION_SAME_EXTENDEE",
			"FILE_SAME_PACKAGE", "FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED", "FIELD_WIRE_COMPATIBLE_TYPE", "FIELD_WIRE_COMPATIBLE_CARDINALITY",
			"FIELD_SAME_ONEOF", "FIELD_SAME_DEFAULT", "ENUM_VALUE_NO_DELETE_UNLESS_NUMBER_RESERVED", "MESSAGE_SAME_REQUIRED_FIELDS",
			"RESERVED_MESSAGE_NO_DELETE", "RESERVED_ENUM_NO_DELETE", "RPC_NO_DELETE", "RPC_SAME_REQUEST_TYPE", "RPC_SAME_RESPONSE_TYPE",
			"RPC_SAME_CLIENT_STREAMING", "RPC_SAME_SERVER_STREAMING", "RPC_SAME_IDEMPOTENCY_LEVEL",
		},
	},
}

// BreakingProfiles returns the supported breaking profiles and their exact rule names.
func BreakingProfiles() []BreakingProfile {
	result := make([]BreakingProfile, len(breakingProfiles))
	for i, profile := range breakingProfiles {
		result[i] = profile
		result[i].Rules = slices.Clone(profile.Rules)
	}
	return result
}

// ValidateBreakingCategories rejects profile names outside the shared catalog.
func ValidateBreakingCategories(categories []string) error {
	for _, category := range categories {
		if !slices.ContainsFunc(breakingProfiles, func(profile BreakingProfile) bool { return profile.Name == category }) {
			return fmt.Errorf("breaking.categories: unknown profile %q; supported: FILE, PACKAGE, WIRE_JSON, WIRE", category)
		}
	}
	return nil
}

// BreakingProfileNames returns the catalog names in strictness order.
func BreakingProfileNames() []string {
	result := make([]string, len(breakingProfiles))
	for i, profile := range breakingProfiles {
		result[i] = profile.Name
	}
	return result
}
